### ISSUE TITLE
global.Express has no exported member 'SessionData'

### ISSUE THREAD

**Issue by itstheandre** [kleydon/prisma-session-store#30] opened 2021-01-10 16:29 UTC
Hey there! I got this error with this session store
 
```node
node_modules/@quixo3/prisma-session-store/dist/lib/prisma-session-store.d.ts:153:64 - error TS2694: Namespace 'global.Express' has no exported member 'SessionData'.
```

I got this error in my projet and I believe its because of the way you built the types 🤔 

Do you know if there is a way to update this somehow?

Thanks

**Comment by wSedlacek** [comment] 2021-01-10 22:55
What version of @types/express do you have installed?

**Comment by itstheandre** [comment] 2021-01-10 23:50
Hey @wSedlacek , these are the current ones:
```json
 "@types/express-session": "1.17.3",
"@types/express": "^4.17.8",
```

The only way i can get to make it work is:
```json
 "@types/express-session": "1.15.16",
"@types/express": "^4.17.8",
```

If i do the express session with that, it works. But not with the most up to date dependencies

**Comment by itstheandre** [comment] 2021-01-10 23:51
I believe this is happening because of the SessionData not being available in the `global.Express` anymore. I saw your PR and it might be the right solution. WOuld need to test it out

**Comment by wSedlacek** [comment] 2021-01-11 00:02
@itstheandre Thank you for notifying us of this issue.
I have recreated it. It appears that `@types/express-session` had some breaking changes since we last updated that package.
I have created a PR to fix this issue, and as you can see from the test it is passing with 100% test coverage.
Once it is merged in your issue should be fixed, but I am looking into how we can assure that compatibly type packages are used in the future either through `dependencies` or `peerDependencies`.

In any case, once the latest version is released, update and reopen this issue if the problem is not fixed.

**Closed** 2021-01-12 15:12 UTC
Labels: dependencies
